Added Test for Data-Web SI and implementation
Notes:
- noticed an exception caused by the aggregated AggregatedAIDaoTest and AggregatedSIDaoTest. If run individually, they passed. However if run one after the other and error would be thrown out.

'''
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["FKAPCW4SB8KS2WVRPU81RYC80PK: PUBLIC.AGGREGATED_AI FOREIGN KEY(TIME_ID) REFERENCES PUBLIC.TIME(ID) (3)"; SQL statement:
delete from time where id=? [23503-197]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
'''

Resolution: calling delete on the aggregated(AI/SI)Dao and timeDao before and after the test case.